import { test, expect } from '@playwright/test';
const { chromium } = require('@playwright/test');
test('test', async ({ page }) => {
  await page.goto('http://localhost:3002/');
  await page.locator('div').filter({ hasText: 'Welcome to ImpactAt Impact,' }).nth(3).click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByLabel('Email:').click();
  await page.getByRole('link', { name: 'Signup' }).click();
  await page.getByPlaceholder('Please enter your name.').click();
  await page.getByPlaceholder('Please enter your name.').press('CapsLock');
  await page.getByPlaceholder('Please enter your name.').fill('V');
  await page.getByPlaceholder('Please enter your name.').press('CapsLock');
  await page.getByPlaceholder('Please enter your name.').fill('Vivek ');
  await page.getByPlaceholder('Please enter your name.').press('CapsLock');
  await page.getByPlaceholder('Please enter your name.').fill('Vivek S');
  await page.getByPlaceholder('Please enter your name.').press('CapsLock');
  await page.getByPlaceholder('Please enter your name.').fill('Vivek Sharma');
  await page.getByLabel('Age:').click();
  await page.getByLabel('Age:').fill('30');
  await page.getByLabel('Gender:').click();
  await page.getByLabel('Gender:').fill('male');
  await page.getByLabel('Smoke:').check();
  await page.getByLabel('Income Per Annum:').click();
  await page.getByLabel('Income Per Annum:').fill('599992');
  await page.getByLabel('Income Per Annum:').click();
  await page.getByLabel('Income Per Annum:').fill('600000');
  await page.getByLabel('Mail:').click();
  await page.getByLabel('Mail:').fill('vivek@sharma.com');
  await page.getByPlaceholder('Password should consist').click();
  await page.getByPlaceholder('Password should consist').fill('vivek@123');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Find Policy' }).click();
  await page.getByRole('button', { name: 'Buy Now' }).click();
  await page.goto('http://localhost:3002/suggested-policy');
  await page.getByRole('link', { name: 'Home' }).click();
});